name: bike_control
description: "BikeControl - Control your virtual riding"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 4.6.2+93

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.3.1
  flutter_local_notifications: ^19.5.0

  # fork to allow iOS background BLE connections
  universal_ble:
    git:
      url: https://github.com/jonasbark/universal_ble.git
  gamepads: ^0.1.8+2

  path_provider: ^2.1.5
  smtc_windows: ^1.1.0
  flutter_volume_controller: ^1.3.4
  intl: any
  version: ^3.0.0
  bluetooth_low_energy: ^6.1.0
  wakelock_plus: ^1.4.0
  protobuf: ^4.2.0
  flutter_md: ^0.0.7
  permission_handler: ^12.0.1
  dartx: any
  nsd: ^4.0.3
  image_picker: ^1.1.2
  in_app_review: ^2.0.11
  ios_receipt:
    path: ios_receipt
  flutter_secure_storage: ^10.0.0
  in_app_purchase: ^3.2.1
  purchases_flutter: ^9.10.2
  purchases_ui_flutter: ^9.10.2
  windows_iap:
    path: windows_iap
  window_manager: ^0.5.1
  device_info_plus: ^12.1.0
  keypress_simulator:
    path: keypress_simulator/packages/keypress_simulator
  shared_preferences: ^2.5.3
  media_key_detector:
    path: media_key_detector/media_key_detector
  accessibility:
    path: accessibility
  sensors_plus: ^7.0.0

  device_auto_rotate_checker:
    git:
      url: https://github.com/mpcreza/device_auto_rotate_checker.git

  # app update related
  shorebird_code_push: ^2.0.5
  restart_app:
    git:
      url: https://github.com/maple135790/restart_app.git
      ref: feature/resolve-all-open-issues
  package_info_plus: ^9.0.0
  in_app_update: ^4.2.5
  http: ^1.3.0
  prop:
    path: prop_public
  shadcn_flutter:
    git:
      url: https://github.com/sunarya-thito/shadcn_flutter.git

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  pubghost: ^1.0.7
  intl_utils: ^2.8.12
  golden_screenshot: ^8.1.1
  flutter_lints: ^6.0.0
  msix: ^3.16.12

dependency_overrides:
  gamepads_windows:
    git:
      url: https://github.com/lea108/gamepads.git
      ref: windows-api-rework
      path: packages/gamepads_windows

flutter:
  uses-material-design: true
  assets:
    - CHANGELOG.md
    - TROUBLESHOOTING.md
    - INSTRUCTIONS_MYWHOOSH_LINK.md
    - INSTRUCTIONS_REMOTE_CONTROL.md
    - INSTRUCTIONS_ROUVY.md
    - INSTRUCTIONS_ZWIFT.md
    - INSTRUCTIONS_LOCAL.md
    - shorebird.yaml
    - icon.png

flutter_intl:
  enabled: true
  arb_dir: lib/i10n
  class_name: AppLocalizations
  output_dir: lib/gen

msix_config:
  display_name: BikeControl
  publisher_display_name: Jonas Bark
  identity_name: JonasBark.SwiftControl
  publisher: CN=EDA6D86E-3E52-4054-9F3A-4277AFCCB2C4
  store: true
  logo_path: web/icons/Icon-512.png
  build_windows: false
  capabilities: internetClient,bluetooth,inputInjectionBrokered
